spring:
  config:
    import: "optional:classpath:application-secret.properties"
  application:
    name: cookbook
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  liquibase:
    change-log: db/changelog/changelog-master.xml
logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
jwt:
  secret: ${jwt.secret}
  lifetime: ${jwt.lifetime}