#Database
db.url=${DB_URL:jdbc:postgresql://localhost:5432/cookbook}
db.username=${DB_USERNAME:postgres}
db.password=${DB_PASSWORD:qwerty}

#JWT
jwt.secret=${JWT_SECRET:D9f7vB3pQx!kL2rZ6wS8uH1mN0yT5aJ4eF@cG7bR2qV8xP6zW3dL9sK0nY1uM}
jwt.access-lifetime-minutes=${JWT_ACCESS_LIFETIME_MINUTES:30}
jwt.refresh-lifetime-days=${JWT_REFRESH_LIFETIME_DAYS:7}

#Mail
mail.username=${MAIL_USERNAME:mashnin.cookbook@mail.ru}
mail.password=${MAIL_PASSWORD:rK1fxijPb2OLm0urM4Dc}
